cursor #d9e4eb
cursor_text_color #bdc8cf

foreground            #d9e4eb
background            #0a151a
selection_foreground  #163349
selection_background  #aec9e6
url_color             #69d3ff

color0   #0a151a
color1   #ff598f
color2   #69ff79
color3   #fff459
color4   #47c0f2
color5   #005376
color6   #69d3ff
color7   #edf9ff
color8   #97a1a5
color9   #ff8eb3
color10  #96ffa1
color11  #fff896
color12  #7fd9ff
color13  #96e0ff
color14  #bbebff
color15  #f7fcff
