github.com:
    git_protocol: https
    users:
        Maverik0071:
            oauth_token: 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
    user: Maverik0071
    oauth_token: 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
